name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    uses: mirenchaps/ci-platform/.github/workflows/static-validate.yml@main
